package adminui;

import java.beans.PropertyVetoException;
import java.util.List;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import model.DAO.screeninfoDAO;
import model.DAO.screenseatinfoDAO;
import model.DAO.seattypeDAO;
import model.to.screeninfoTO;
import model.to.screenseatinfoTO;
import model.to.seattypeTO;
import operations.Validations;

/**
 *
 * @author Shubham Sethi
 */
public class AddScreenSeat extends javax.swing.JInternalFrame {

    public AddScreenSeat(screenseatinfoTO cit) {
        this();
        if (cit != null) {
            jtfSeatName.setText(cit.getSeatname());
            for(int i = 1; i < jcbScreenName.getItemCount(); i++){
                screeninfoTO mit = (screeninfoTO)jcbScreenName.getItemAt(i);
                if(mit.getScreenID().equals(cit.getScreenID())){
                    jcbScreenName.setSelectedIndex(i);
                    break;
                }
            }
            jcbScreenName.setSelectedItem(cit.getScreenname());
            for(int i = 1; i < jcbSeatType.getItemCount(); i++){
                seattypeTO mit = (seattypeTO)jcbSeatType.getItemAt(i);
                if(mit.getTypeID()== cit.getTypeID()){
                    jcbSeatType.setSelectedIndex(i);
                    break;
                }
            }
            jcbSeatType.setSelectedItem(cit.getSeattype());
            setTitle("Update Screen Seat Information");
            btnScreenSeat.setText("Update");
        }
    }

    public AddScreenSeat() {
        initComponents();
        getRootPane().setDefaultButton(btnScreenSeat);
        jcbScreenName.removeAllItems();
        jcbScreenName.addItem("Choose Screen");
        jcbSeatType.removeAllItems();
        jcbSeatType.addItem("Choose Seat Type");
        List<screeninfoTO> screens = new screeninfoDAO().getAllRecord();
        //List<seattypeTO> seats = new seattypeDAO().getAllRecord();
        if (screens != null && screens.size() > 0) {
            for (screeninfoTO ssit : screens) {
                jcbScreenName.addItem(ssit);
            }
        }
        /*if (seats != null && seats.size() > 0) {
            for (seattypeTO sit : seats) {
                jcbSeatType.addItem(sit);
            }
        }*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnScreenSeat = new javax.swing.JButton();
        jtfSeatName = new javax.swing.JTextField();
        jcbScreenName = new javax.swing.JComboBox<>();
        jcbSeatType = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setTitle("Add Screen Seat Information");
        setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Enter Seat Name");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Choose Screen Name");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Choose Seat Type");

        btnScreenSeat.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        btnScreenSeat.setText("Add Screen Seat");
        btnScreenSeat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnScreenSeatActionPerformed(evt);
            }
        });

        jcbScreenName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbScreenName.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbScreenNameItemStateChanged(evt);
            }
        });

        jcbSeatType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfSeatName)
                            .addComponent(jcbScreenName, 0, 324, Short.MAX_VALUE)
                            .addComponent(jcbSeatType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(btnScreenSeat)))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfSeatName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jcbScreenName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jcbSeatType, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addComponent(btnScreenSeat, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnScreenSeatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnScreenSeatActionPerformed
        String message = "";
        boolean allvalid = true;
        String seat = jtfSeatName.getText().trim();
        if (Validations.isEmpty(seat)) {
            message += "Please Enter Any Seat Name\n\n";
            allvalid = false;
        }
        if (jcbScreenName.getSelectedIndex() == 0) {
            message += "Please Choose Any Screen\n\n";
            allvalid = false;
        }
        if (jcbSeatType.getSelectedIndex() == 0) {
            message += "Please Choose Any Seat";
            allvalid = false;
        }
        if (allvalid) {
            screeninfoTO cit = (screeninfoTO) jcbScreenName.getSelectedItem();
            seattypeTO sit = (seattypeTO) jcbSeatType.getSelectedItem();
            screenseatinfoTO ssi = new screenseatinfoTO();
            ssi.setSeatname(seat);
            ssi.setScreenID(cit.getScreenID());
            ssi.setTypeID(sit.getTypeID());
            screenseatinfoDAO action = new screenseatinfoDAO();
            if (btnScreenSeat.getText().contains("Add")) {
                if (action.insertRecord(ssi)) {
                    message = "This Screen is Assigned with Entered Seatname";
                    jcbScreenName.setSelectedIndex(0);
                    jtfSeatName.setText("");
                    JInternalFrame[] jif = getDesktopPane().getAllFrames();
                    if (jif != null) {
                        for (JInternalFrame jf : jif) {
                            if (jf instanceof ViewMovieTiming) {
                                ViewMovieTiming vci = (ViewMovieTiming) jf;
                                vci.bindTimingTable();
                                break;
                            }
                        }
                    }
                } else {
                    message = action.getErrormessgae();
                }
            } else if (btnScreenSeat.getText().contains("Update")) {
                if (action.updateRecord(ssi)) {
                    message = "Screen Seat Information is Updated in System";
                    jcbScreenName.setSelectedIndex(0);
                    jtfSeatName.setText("");
                } else {
                    message = action.getErrormessgae();
                }
                ViewScreenSeat vci = new ViewScreenSeat();
                vci.setVisible(true);
                getDesktopPane().add(vci);
                try {
                    vci.setSelected(true);
                } catch (PropertyVetoException ex) {
                }
                dispose();
            }
        }
        JOptionPane.showMessageDialog(this, message);
    }//GEN-LAST:event_btnScreenSeatActionPerformed

    private void jcbScreenNameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbScreenNameItemStateChanged
        jcbSeatType.removeAllItems();
        jcbSeatType.addItem("Choose Seat Type");
        if (!(jcbScreenName.getSelectedIndex() == 0)) {
            List<seattypeTO> seats = new seattypeDAO().getAllRecord();
            if (seats != null && seats.size() > 0) {
                for (seattypeTO sit : seats) {
                    jcbSeatType.addItem(sit);
                }
            }
        }
    }//GEN-LAST:event_jcbScreenNameItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnScreenSeat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox<Object> jcbScreenName;
    private javax.swing.JComboBox<Object> jcbSeatType;
    private javax.swing.JTextField jtfSeatName;
    // End of variables declaration//GEN-END:variables
}
