package adminui;

import java.beans.PropertyVetoException;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import model.DAO.screeninfoDAO;
import model.to.screeninfoTO;
import operations.Validations;

/**
 *
 * @author Shubham Sethi
 */
public class AddScreenInfo extends javax.swing.JInternalFrame {

    public AddScreenInfo() {
        initComponents();
        getRootPane().setDefaultButton(btnAddScreenInfo);
    }

    public AddScreenInfo(screeninfoTO cit) {
        this();
        if (cit != null) {
            jtfScreenID.setText(cit.getScreenID());
            jtfScreenName.setText(cit.getScreenname());
            jtfTotalSeats.setText(String.valueOf(cit.getTotalseats()));
            jtfScreenID.setEditable(false);
            setTitle("Update Screen Information");
            btnAddScreenInfo.setText("Update");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtfLabel1 = new javax.swing.JLabel();
        jtfLabel2 = new javax.swing.JLabel();
        jtfLabel3 = new javax.swing.JLabel();
        btnAddScreenInfo = new javax.swing.JButton();
        jtfScreenID = new javax.swing.JTextField();
        jtfScreenName = new javax.swing.JTextField();
        jtfTotalSeats = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setTitle("Add Screen Information");

        jtfLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jtfLabel1.setText("Enter Screen ID");

        jtfLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jtfLabel2.setText("Enter Screen Name");

        jtfLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jtfLabel3.setText("Enter Total Seats");

        btnAddScreenInfo.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnAddScreenInfo.setText("Add New Screen");
        btnAddScreenInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddScreenInfoActionPerformed(evt);
            }
        });

        jtfScreenID.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jtfScreenID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfScreenIDKeyTyped(evt);
            }
        });

        jtfScreenName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jtfTotalSeats.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jtfTotalSeats.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfTotalSeatsKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfLabel2)
                            .addComponent(jtfLabel1)
                            .addComponent(jtfLabel3))
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfScreenName, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfScreenID, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfTotalSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(btnAddScreenInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfLabel1)
                    .addComponent(jtfScreenID, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfLabel2)
                    .addComponent(jtfScreenName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfLabel3)
                    .addComponent(jtfTotalSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addComponent(btnAddScreenInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddScreenInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddScreenInfoActionPerformed
        String screenid = jtfScreenID.getText().trim();
        String screenname = jtfScreenName.getText().trim();
        String totalseats = jtfTotalSeats.getText().trim();
        boolean allvalid = true;
        String message = "";
        if (Validations.isEmpty(screenid)) {
            message+= "Please Provide Screen ID\n\n";
            allvalid = false;
        }
        if (Validations.isEmpty(screenname)) {
            message+= "Please Provide Screen Name\n\n";
            allvalid = false;
        }
        if (Validations.isEmpty(totalseats)) {
            message+= "Please Provide No. of Seats\n\n";
            allvalid = false;
        }
        if (allvalid) {
            int seats = Integer.parseInt(totalseats);
            if (seats > 0) {
                screeninfoTO sit = new screeninfoTO();
                sit.setScreenID(screenid);
                sit.setScreenname(screenname);
                sit.setTotalseats(seats);
                screeninfoDAO action = new screeninfoDAO();
                if (btnAddScreenInfo.getText().contains("Add")) {
                    if (action.insertRecord(sit)) {
                        message = "New Screen Information is added in system";
                        jtfScreenID.setText("");
                        jtfScreenName.setText("");
                        jtfTotalSeats.setText("");
                        JInternalFrame[] jif = getDesktopPane().getAllFrames();
                        if (jif != null) {
                            for (JInternalFrame jf : jif) {
                                if (jf instanceof ViewScreenInfo) {
                                    ViewScreenInfo vci = (ViewScreenInfo) jf;
                                    vci.bindScreenTable();
                                    break;
                                }
                            }
                        }
                    } else {
                        message = action.getErrormessgae();
                    }
                } else if (btnAddScreenInfo.getText().contains("Update")) {
                    if (action.updateRecord(sit)) {
                        message = "Screen Details are Updated in System";
                        jtfScreenID.setText("");
                        jtfScreenName.setText("");
                        jtfTotalSeats.setText("");
                    } else {
                        message = action.getErrormessgae();
                    }
                    ViewScreenInfo vci = new ViewScreenInfo();
                    vci.setVisible(true);
                    getDesktopPane().add(vci);
                    try {
                        vci.setSelected(true);
                    } catch (PropertyVetoException ex) {
                    }
                    dispose();
                }
            }
        }
        JOptionPane.showMessageDialog(this, message);
    }//GEN-LAST:event_btnAddScreenInfoActionPerformed

    private void jtfTotalSeatsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfTotalSeatsKeyTyped
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_jtfTotalSeatsKeyTyped

    private void jtfScreenIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfScreenIDKeyTyped
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_jtfScreenIDKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddScreenInfo;
    private javax.swing.JLabel jtfLabel1;
    private javax.swing.JLabel jtfLabel2;
    private javax.swing.JLabel jtfLabel3;
    private javax.swing.JTextField jtfScreenID;
    private javax.swing.JTextField jtfScreenName;
    private javax.swing.JTextField jtfTotalSeats;
    // End of variables declaration//GEN-END:variables
}
