package adminui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.beans.PropertyVetoException;
import java.util.List;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.table.DefaultTableModel;
import model.DAO.movieinfoDAO;
import model.to.movieinfoTO;

/**
 *
 * @author Shubham Sethi
 */
public class ViewMovieInfo extends javax.swing.JInternalFrame {

    List<movieinfoTO> movies;
    int row;
    private JPopupMenu popupmenu;

    public ViewMovieInfo() {
        initComponents();
        bindMovieTable();
        row = -1;
        popupmenu = new JPopupMenu();
        JMenuItem jmiDelete = new JMenuItem("Delete This Record");
        JMenuItem jmiEdit = new JMenuItem("Edit This Record");
        jmiDelete.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                deleteRecord();
            }

        });
        jmiEdit.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                editRecord();
            }

        });
        popupmenu.add(jmiDelete);
        popupmenu.add(jmiEdit);
    }

    private void editRecord() {
        if (row != -1 && movies != null && row < movies.size()) {
            movieinfoTO cit = movies.get(row);
            AddMovieInfo aci = new AddMovieInfo(cit);
            aci.setVisible(true);
            getDesktopPane().add(aci);
            try {
                aci.setSelected(true);
            } catch (PropertyVetoException ex) {

            }
            dispose();
        }
    }

    private void deleteRecord() {
        if (row != -1 && movies != null && row < movies.size()) {
            int result = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this record?", "Confirm Delete?", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (result == JOptionPane.YES_OPTION) {
                movieinfoTO cit = movies.get(row);
                if (cit != null) {
                    String message = "";
                    movieinfoDAO action = new movieinfoDAO();
                    if (action.deleteRecord(String.valueOf(cit.getMovieID()))) {
                        message = "Selected Movie Information is Removed from System";
                        bindMovieTable();
                    } else {
                        message = action.getErrormessgae();
                    }
                    JOptionPane.showMessageDialog(this, message);
                }
            }
        }
        row = -1;
    }

    public void bindMovieTable() {
        movies = new movieinfoDAO().getAllRecord();
        String[] colnames = {"Movie Name", "Description", "Release Date", "End Date"};
        Object[][] records = null;
        if (movies != null && movies.size() > 0) {
            records = new Object[movies.size()][colnames.length];
            int i = 0;
            for (movieinfoTO mit : movies) {
                records[i] = new Object[]{mit.getMoviename(), mit.getDescription(), mit.getReleasedate(), mit.getEnddate()};
                i++;
            }
        } else {
            records = new Object[1][colnames.length];
            records[0] = new Object[]{"No Records", "No Records", "No Records", "No Records"};
        }
        DefaultTableModel dtm = new DefaultTableModel(records, colnames) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tableMovieInfo.getTableHeader().setReorderingAllowed(false);
        tableMovieInfo.setAutoCreateRowSorter(true);
        tableMovieInfo.setModel(dtm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableMovieInfo = new javax.swing.JTable();
        btnRefresh = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("View Movie Information");

        tableMovieInfo.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tableMovieInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableMovieInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMovieInfoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableMovieInfo);

        btnRefresh.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 712, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        bindMovieTable();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void tableMovieInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMovieInfoMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON3) {
            int rowpos = tableMovieInfo.rowAtPoint(evt.getPoint());
            tableMovieInfo.getSelectionModel().setSelectionInterval(rowpos, rowpos);
            popupmenu.show(tableMovieInfo, evt.getX(), evt.getY());
            row = tableMovieInfo.getSelectedRow();
        }
    }//GEN-LAST:event_tableMovieInfoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefresh;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableMovieInfo;
    // End of variables declaration//GEN-END:variables
}
