package adminui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.beans.PropertyVetoException;
import java.util.List;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.table.DefaultTableModel;
import model.DAO.seattypeDAO;
import model.to.seattypeTO;

/**
 *
 * @author Shubham Sethi
 */
public class ViewSeatType extends javax.swing.JInternalFrame {

    List<seattypeTO> seats;
    int row;
    private JPopupMenu popupmenu;

    public ViewSeatType() {
        initComponents();
        bindSeatTable();
        row = -1;
        popupmenu = new JPopupMenu();
        JMenuItem jmiDelete = new JMenuItem("Delete This Record");
        JMenuItem jmiEdit = new JMenuItem("Edit This Record");
        jmiDelete.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                deleteRecord();
            }
        });
        jmiEdit.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                editRecord();
            }
        });
        popupmenu.add(jmiDelete);
        popupmenu.add(jmiEdit);
    }
    
    private void editRecord() {
        if (row != -1 && seats != null && row < seats.size()) {
            seattypeTO cit = seats.get(row);
            AddSeatType aci = new AddSeatType(cit);
            aci.setVisible(true);
            getDesktopPane().add(aci);
            try {
                aci.setSelected(true);
            } catch (PropertyVetoException ex) {

            }
            dispose();
        }
    }
    
    private void deleteRecord() {
        if (row != -1 && seats != null && row < seats.size()) {
            int result = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this record?", "Confirm Delete?", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if(result == JOptionPane.YES_OPTION){
                seattypeTO cit = seats.get(row);
                if(cit!=null){
                    String message = "";
                    seattypeDAO action = new seattypeDAO();
                    if(action.deleteRecord(String.valueOf(cit.getTypeID()))){
                        message = "Selected Seat Type is Removed from System";
                        bindSeatTable();
                    }else{
                        message = action.getErrormessgae();
                    }
                    JOptionPane.showMessageDialog(this, message);
                }
            }
        }
        row = -1;
    }

    public void bindSeatTable() {
        seats = new seattypeDAO().getAllRecord();
        String[] colnames = {"Type Name", "Charges"};
        Object[][] records = null;
        if (seats != null && seats.size() > 0) {
            records = new Object[seats.size()][colnames.length];
            int i = 0;
            for (seattypeTO sit : seats) {
                records[i] = new Object[]{sit.getTypename(), sit.getCharges()};
                i++;
            }
        } else {
            records = new Object[1][colnames.length];
            records[0] = new Object[]{"No Records", "No Records"};
        }
        DefaultTableModel dtm = new DefaultTableModel(records, colnames) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tableSeatType.getTableHeader().setReorderingAllowed(false);
        tableSeatType.setAutoCreateRowSorter(true);
        tableSeatType.setModel(dtm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRefresh = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableSeatType = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setTitle("View Seat Types");

        btnRefresh.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        tableSeatType.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tableSeatType.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableSeatType.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableSeatTypeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableSeatType);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 712, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        bindSeatTable();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void tableSeatTypeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableSeatTypeMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON3) {
            int rowpos = tableSeatType.rowAtPoint(evt.getPoint());
            tableSeatType.getSelectionModel().setSelectionInterval(rowpos, rowpos);
            popupmenu.show(tableSeatType, evt.getX(), evt.getY());
            row = tableSeatType.getSelectedRow();
        }
    }//GEN-LAST:event_tableSeatTypeMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefresh;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableSeatType;
    // End of variables declaration//GEN-END:variables
}
