package adminui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.beans.PropertyVetoException;
import java.util.List;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.table.DefaultTableModel;
import model.DAO.screeninfoDAO;
import model.to.screeninfoTO;

/**
 *
 * @author Shubham Sethi
 */
public class ViewScreenInfo extends javax.swing.JInternalFrame {

    List<screeninfoTO> screens;
    int row;
    private JPopupMenu popupmenu;

    public ViewScreenInfo() {
        initComponents();
        bindScreenTable();
        row = -1;
        popupmenu = new JPopupMenu();
        JMenuItem jmiDelete = new JMenuItem("Delete This Record");
        JMenuItem jmiEdit = new JMenuItem("Edit This Record");
        jmiDelete.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                deleteRecord();
            }
        });
        jmiEdit.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                editRecord();
            }
        });
        popupmenu.add(jmiDelete);
        popupmenu.add(jmiEdit);
    }
    
    private void editRecord() {
        if (row != -1 && screens != null && row < screens.size()) {
            screeninfoTO cit = screens.get(row);
            AddScreenInfo aci = new AddScreenInfo(cit);
            aci.setVisible(true);
            getDesktopPane().add(aci);
            try {
                aci.setSelected(true);
            } catch (PropertyVetoException ex) {

            }
            dispose();
        }
    }
    
    private void deleteRecord() {
        if (row != -1 && screens != null && row < screens.size()) {
            int result = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this record?", "Confirm Delete?", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if(result == JOptionPane.YES_OPTION){
                screeninfoTO cit = screens.get(row);
                if(cit!=null){
                    String message = "";
                    screeninfoDAO action = new screeninfoDAO();
                    if(action.deleteRecord(cit.getScreenID())){
                        message = "Selected Screen Information is Removed from System";
                        bindScreenTable();
                    }else{
                        message = action.getErrormessgae();
                    }
                    JOptionPane.showMessageDialog(this, message);
                }
            }
        }
        row = -1;
    }

    public void bindScreenTable() {
        screens = new screeninfoDAO().getAllRecord();
        String[] colnames = {"Screen ID","Screen Name","Total Seats"};
        Object[][] records = null;
        if (screens != null && screens.size() > 0) {
            records = new Object[screens.size()][colnames.length];
            int i = 0;
            for (screeninfoTO sit : screens) {
                records[i] = new Object[]{sit.getScreenID(), sit.getScreenname(), sit.getTotalseats()};
                i++;
            }
        } else {
            records = new Object[1][colnames.length];
            records[0] = new Object[]{"No Records", "No Records", "No Records"};
        }
        DefaultTableModel dtm = new DefaultTableModel(records, colnames) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tableScreenInfo.getTableHeader().setReorderingAllowed(false);
        tableScreenInfo.setAutoCreateRowSorter(true);
        tableScreenInfo.setModel(dtm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableScreenInfo = new javax.swing.JTable();
        btnRefresh = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("View Screen Information");

        tableScreenInfo.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tableScreenInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableScreenInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableScreenInfoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableScreenInfo);

        btnRefresh.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 712, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        bindScreenTable();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void tableScreenInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableScreenInfoMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON3) {
            int rowpos = tableScreenInfo.rowAtPoint(evt.getPoint());
            tableScreenInfo.getSelectionModel().setSelectionInterval(rowpos, rowpos);
            popupmenu.show(tableScreenInfo, evt.getX(), evt.getY());
            row = tableScreenInfo.getSelectedRow();
        }
    }//GEN-LAST:event_tableScreenInfoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefresh;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableScreenInfo;
    // End of variables declaration//GEN-END:variables
}
