package userui;

import java.awt.Color;
import java.awt.GridLayout;
import java.sql.Date;
import java.sql.Time;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.List;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import model.DAO.bookingdetailsDAO;
import model.DAO.bookinginfoDAO;
import model.DAO.movieinfoDAO;
import model.DAO.movietimingDAO;
import model.DAO.screenseatinfoDAO;
import model.to.bookingdetailsTO;
import model.to.bookinginfoTO;
import model.to.movieinfoTO;
import model.to.movietimingTO;
import model.to.screenseatinfoTO;

/**
 *
 * @author Shubham Sethi
 */
public class Booking extends javax.swing.JInternalFrame {

    String movieid = null;
    GregorianCalendar gcal;
    List<JCheckBox> seats;
    List<screenseatinfoTO> screens;
    String tickets = "";
    String price = "";

    public Booking() {
        initComponents();
        gcal = new GregorianCalendar();
        getRootPane().setDefaultButton(btnBookTicket);
        jcbMovies.removeAllItems();
        jcbMovies.addItem("Choose Movie");
        jcbTimings.removeAllItems();
        jcbTimings.addItem("Choose Timing");
        jcbScreens.removeAllItems();
        jcbScreens.addItem("Choose Screen");
        jcbDates.removeAllItems();
        jcbDates.addItem("Choose Date");
        setTitle("New Ticket Booking");
        jtfPrice.setText("0");
        jtfTickets.setText("0");
        jtfPrice.setEditable(false);
        jtfTickets.setEditable(false);
        List<movieinfoTO> movies = new movieinfoDAO().getCurrentRecord();
        if (movies != null && movies.size() > 0) {
            for (movieinfoTO mit : movies) {
                jcbMovies.addItem(mit);
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcbMovies = new javax.swing.JComboBox<>();
        btnBookTicket = new javax.swing.JButton();
        jcbTimings = new javax.swing.JComboBox<>();
        jcbScreens = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jcbDates = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        myPanel = new javax.swing.JPanel();
        btnUpdate = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtfTickets = new javax.swing.JTextField();
        jtfPrice = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);

        jcbMovies.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbMovies.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbMoviesItemStateChanged(evt);
            }
        });

        btnBookTicket.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnBookTicket.setText("Book Tickets");
        btnBookTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookTicketActionPerformed(evt);
            }
        });

        jcbTimings.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbTimings.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbTimingsItemStateChanged(evt);
            }
        });

        jcbScreens.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbScreens.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbScreensItemStateChanged(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setText("Select Movie");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setText("Select Screen");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setText("Select Timing");

        jcbDates.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbDates.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbDatesItemStateChanged(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel4.setText("Select Date");

        javax.swing.GroupLayout myPanelLayout = new javax.swing.GroupLayout(myPanel);
        myPanel.setLayout(myPanelLayout);
        myPanelLayout.setHorizontalGroup(
            myPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 593, Short.MAX_VALUE)
        );
        myPanelLayout.setVerticalGroup(
            myPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 348, Short.MAX_VALUE)
        );

        btnUpdate.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        jLabel5.setForeground(java.awt.Color.red);
        jLabel5.setText("Click on update button after selecting seats");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(java.awt.Color.blue);
        jLabel6.setText("No. of tickets");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(java.awt.Color.blue);
        jLabel7.setText("Price of tickets selected");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addGap(128, 128, 128)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jcbMovies, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)
                                        .addComponent(jLabel5))
                                    .addComponent(jcbTimings, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jcbScreens, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jcbDates, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(82, 82, 82)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jtfTickets, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jtfPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel7))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(625, 625, 625)
                                .addComponent(btnBookTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(myPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jcbMovies, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jcbTimings, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jcbScreens, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcbDates, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(41, 41, 41)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jtfTickets, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jtfPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addComponent(btnBookTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(myPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbMoviesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbMoviesItemStateChanged
        jcbTimings.removeAllItems();
        jcbTimings.addItem("Choose Timing");
        if (!(jcbMovies.getSelectedIndex() == 0)) {
            try {
                movieinfoTO m = (movieinfoTO) jcbMovies.getSelectedItem();
                movieid = String.valueOf(m.getMovieID());
            } catch (NullPointerException npe) {
            }

            List<movietimingTO> timings = new movietimingDAO().getCurrentTimes(movieid);
            if (timings != null && timings.size() > 0) {
                int a = 0;
                for (movietimingTO sit : timings) {
                    jcbTimings.addItem(sit.toString(a));
                }
            }
        }
    }//GEN-LAST:event_jcbMoviesItemStateChanged

    private void btnBookTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookTicketActionPerformed
        /*movietimingTO m = null;
        if(jcbScreens.getSelectedIndex()!=0){
            m = (movietimingTO) jcbScreens.getSelectedItem();
        }
        screens = new screenseatinfoDAO().getRecords(m.getScreenID());*/

        String message = "";
        boolean allvalid = true;
        if (jcbMovies.getSelectedIndex() == 0) {
            message += "Please Choose Any Movie\n\n";
            allvalid = false;
        }
        if (jcbTimings.getSelectedIndex() == 0) {
            message += "Please Choose Any Movie Timing\n\n";
            allvalid = false;
        }
        if (jcbScreens.getSelectedIndex() == 0) {
            message += "Please Choose Any Screen\n\n";
            allvalid = false;
        }
        if (jcbDates.getSelectedIndex() == 0) {
            message += "Please Choose Any Valid Date\n\n";
            allvalid = false;
        }
        if (jtfPrice.getText().isEmpty()) {
            message += "Please Check the Price of Tickets First\n\n";
            allvalid = false;
        }
        List<String> selectedseats = new ArrayList<>();
        if (jcbDates.getSelectedIndex() != 0) {
            for (JCheckBox jcb : seats) {
                if (jcb.isSelected()) {
                    selectedseats.add(jcb.getText());
                }
            }
        }
        if (selectedseats.isEmpty()) {
            message += "Please Select Any Seats";
            allvalid = false;
        }
        if (allvalid) {
            movieinfoTO mit = (movieinfoTO) jcbMovies.getSelectedItem();
            movietimingTO mtt = (movietimingTO) jcbScreens.getSelectedItem();
            Time st = (Time) jcbTimings.getSelectedItem();
            String date = (String) jcbDates.getSelectedItem();
            String[] values = date.split("-");
            int curdate = Integer.parseInt(values[0]);
            int curmonth = gcal.get(Calendar.MONTH) + 1;
            int curyear = gcal.get(Calendar.YEAR);
            String datevalue = curyear + "-" + curmonth + "-" + curdate;
            Date sd = Date.valueOf(datevalue);
            java.util.Date dat = new java.util.Date();
            Timestamp time;
            time = new Timestamp(dat.getTime());
            bookinginfoTO bit = new bookinginfoTO();
            bit.setMovieID(mit.getMovieID());
            bit.setScreenID(mtt.getScreenID());
            bit.setStarttime(st);
            bit.setBookingdate(time);
            bit.setShowdate(sd);
            bookinginfoDAO action = new bookinginfoDAO();
            bookingdetailsDAO act = new bookingdetailsDAO();
            bookingdetailsTO bdt = new bookingdetailsTO();
            if (action.insertRecord(bit)) {
                int bookingid = action.getBookingID();
                if (bookingid != 0) {
                    bdt.setBookingID(bookingid);
                    for (String seatid : selectedseats) {
                        bdt.setSeatname(seatid);
                        act.insertRecord(bdt);
                    }
                }
                message = "Selected Tickets have been booked";
                jcbMovies.setSelectedIndex(0);
                jtfPrice.setText("0");
                jtfTickets.setText("0");
            } else {

                message = action.getErrormessgae();
            }
        }
        JOptionPane.showMessageDialog(this, message);
    }//GEN-LAST:event_btnBookTicketActionPerformed

    private void jcbTimingsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbTimingsItemStateChanged
        jcbScreens.removeAllItems();
        jcbScreens.addItem("Choose Screen");
        if (!(jcbTimings.getSelectedIndex() == 0)) {
            try {
                Time mt = (Time) jcbTimings.getSelectedItem();
                List<movietimingTO> screens = new movietimingDAO().getCurrentRecord(movieid, mt);
                if (screens != null && screens.size() > 0) {
                    for (movietimingTO sit : screens) {
                        jcbScreens.addItem(sit);
                    }
                }
            } catch (NullPointerException n) {
            }
        }
    }//GEN-LAST:event_jcbTimingsItemStateChanged

    private void jcbScreensItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbScreensItemStateChanged
        jcbDates.removeAllItems();
        jcbDates.addItem("Choose Date");
        if (!(jcbScreens.getSelectedIndex() == 0)) {
            int curdate = gcal.get(Calendar.DATE);
            int curmonth = gcal.get(Calendar.MONTH) + 1;
            int curyear = gcal.get(Calendar.YEAR);
            String monthname = null;
            switch (curmonth) {
                case 1:
                    monthname = "January";
                    break;
                case 2:
                    monthname = "February";
                    break;
                case 3:
                    monthname = "March";
                    break;
                case 4:
                    monthname = "April";
                    break;
                case 5:
                    monthname = "May";
                    break;
                case 6:
                    monthname = "June";
                    break;
                case 7:
                    monthname = "July";
                    break;
                case 8:
                    monthname = "August";
                    break;
                case 9:
                    monthname = "September";
                    break;
                case 10:
                    monthname = "October";
                    break;
                case 11:
                    monthname = "November";
                    break;
                case 12:
                    monthname = "December";
                    break;
                default:
                    monthname = "Choose Date";
            }
            for (int i = 0; i < 7; i++) {
                jcbDates.addItem(curdate + "-" + monthname + "-" + curyear);
                curdate++;
            }
        }
    }//GEN-LAST:event_jcbScreensItemStateChanged

    private void jcbDatesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbDatesItemStateChanged
        myPanel.removeAll();
        if (jcbDates.getSelectedIndex() > 0 && jcbScreens.getSelectedIndex() > 0) {
            movieinfoTO mit = (movieinfoTO) jcbMovies.getSelectedItem();
            String mid = String.valueOf(mit.getMovieID());
            Time st = (Time) jcbTimings.getSelectedItem();
            movietimingTO mtt = (movietimingTO) jcbScreens.getSelectedItem();
            screens = new screenseatinfoDAO().getRecords(mtt.getScreenID());
            String date = (String) jcbDates.getSelectedItem();
            String[] values = date.split("-");
            int curdate = Integer.parseInt(values[0]);
            int curmonth = gcal.get(Calendar.MONTH) + 1;
            int curyear = gcal.get(Calendar.YEAR);
            String datevalue = curyear + "-" + curmonth + "-" + curdate;
            Date sd = Date.valueOf(datevalue);
            List<String> bookedseats = new bookingdetailsDAO().getAllRecord(mid, mtt.getScreenID(), st, sd);
            if (screens != null && screens.size() > 0) {
                int row = screens.size() / 10 + 1;
                seats = new ArrayList<>();
                GridLayout layout = new GridLayout(row, 10, 10, 10);
                myPanel.setLayout(layout);
                for (screenseatinfoTO sit : screens) {
                    JCheckBox jcb = new JCheckBox(sit.getSeatname());
                    jcb.setBackground(Color.GREEN);
                    if (bookedseats != null && bookedseats.contains(sit.getSeatname())) {
                        jcb.setBackground(Color.red);
                        jcb.setForeground(Color.yellow);
                        jcb.setEnabled(false);
                    }
                    jcb.setOpaque(true);
                    myPanel.add(jcb);
                    seats.add(jcb);
                }
                myPanel.updateUI();
            }
        }
    }//GEN-LAST:event_jcbDatesItemStateChanged

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try {
            int i = 0, p = 0, ret = 0;
            movietimingTO mit = null;
            String sid = "";
            if (jcbScreens.getSelectedIndex() != 0) {
                mit = (movietimingTO) jcbScreens.getSelectedItem();
                sid = mit.getScreenID();
            }
            screenseatinfoDAO ssid = new screenseatinfoDAO();

            //List<String> chosenseats = new ArrayList<>();
            String message = "";
            for (JCheckBox jcb : seats) {
                if (jcb.isSelected()) {
                    //chosenseats.add(jcb.getText());
                    ret = ssid.getPrice(sid, jcb.getText());
                    p = p + ret;
                    i++;
                }
            }
            if (i == 0) {
                message += "Please select any seats before clicking on Update button!";
                JOptionPane.showMessageDialog(this, message);
            }
            tickets = String.valueOf(i);
            price = String.valueOf(p);
            jtfPrice.setText(price);
            jtfTickets.setText(tickets);
        } catch (NullPointerException n) {
        }
    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBookTicket;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JComboBox<Object> jcbDates;
    private javax.swing.JComboBox<Object> jcbMovies;
    private javax.swing.JComboBox<Object> jcbScreens;
    private javax.swing.JComboBox<Object> jcbTimings;
    private javax.swing.JTextField jtfPrice;
    private javax.swing.JTextField jtfTickets;
    private javax.swing.JPanel myPanel;
    // End of variables declaration//GEN-END:variables
}
